# Generated by Django 4.0.2 on 2022-08-10 19:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_location_remove_user_about_remove_user_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('cuisine_id', models.AutoField(primary_key=True, serialize=False)),
                ('cuisine_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('offer_id', models.AutoField(primary_key=True, serialize=False)),
                ('discount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('hash', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('avg_time', models.CharField(max_length=4)),
                ('avg_cost', models.CharField(max_length=5)),
                ('is_exclusive', models.BooleanField(default=False)),
                ('phone', models.CharField(max_length=10)),
                ('r_logo', models.FileField(blank=True, upload_to='')),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.cuisine')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.location')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.offer')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.restaurantowner')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('instructions', models.TextField(blank=True)),
                ('payment_mode_online', models.BooleanField(default=True)),
                ('tax', models.IntegerField()),
                ('rating', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('review', models.TextField(default='', max_length=250)),
                ('status', models.CharField(choices=[('Placed', 'Placed'), ('Acknowledged', 'Acknowledged'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Dispatched', 'Dispatched')], default='Placed', max_length=50)),
                ('offer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.offer')),
                ('payment_hash', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.payment')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.customer')),
            ],
        ),
        migrations.CreateModel(
            name='FoodRestaurant',
            fields=[
                ('food_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('cost', models.IntegerField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('food_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('is_veg', models.BooleanField(default=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.itemtype')),
            ],
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fooditem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.order')),
            ],
            options={
                'unique_together': {('food_item', 'order')},
            },
        ),
    ]
